data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw'

model:
  name: 'layer1_width300_lr0001_wd000001_raw'
  hidden_layer_nodes: [300]
  input_shape_factor: 21

training:
  learning_rate: 0.001
  wieght_decay: 0.0001
  epochs: 200
  batch_size: 8192
  early_stopping_patience: 15

