data:
  file_path: 'data/raw/HIGGS.csv'
  feature_set: 'raw' # raw/high/all
  
  # remove for full data access  
  num_train_samples: 100000
  num_valid_samples: 20000

model:
  name: 'template'
  hidden_layer_nodes: [128, 64]
  input_shape_factor: 21 # 21/7/28

training:
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  batch_size: 512
  early_stopping_patience: 15

